version: '2'
services:
  db:
    image: rethinkdb
    volumes:
      - ./sharddb:/data
  shard:
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=production
      - SHARD_DB_HOST=db
      - SHARD_DB_NAME=sharddb
      - SHARD_DB_TIMEOUT=10000
      - SHARD_MAIL_VALIDATION=0
      - SHARD_MAIL_HOST=mail.server.com
      - SHARD_MAIL_PORT=465
      - SHARD_MAIL_SECURE=1
      - SHARD_MAIL_USER=user@server.com
      - SHARD_MAIL_PASS=pass
      - SHARD_JWT_SECRET=default-jwt-secret
      - SHARD_AUTH_SALT=Jst#ULN9&HD!NZ0g
      - SHARD_SOCKET_PINGTIME=30000
      - SHARD_GCM_KEY=gcm_key
      - SHARD_GCM_ID=gcm_id
